site_name: Thinking in Types
docs_dir: Chapters
site_url: https://ThinkingInTypes.github.io
repo_url: https://github.com/ThinkingInTypes/ThinkingInTypes.github.io

theme:
  name: material
  favicon: img/favicon.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes  # Ensures only one entry in TOC
    # - toc.integrate  # Makes TOC part of the left-hand navigation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"


nav:
  - 01 Preface.md
  - 02 Foundations.md
  - 03 What_is_a_Type.md
  - 04 Basic_Annotations.md
  - 05 Collections.md
  - 06 Generics.md
  - 07 Dataclasses.md
  - 08 Specialized_Type_Tools.md
  - 09 Callables.md
  - 10 Structural_Typing.md
  - 11 Make_Illegal_Types_Unrepresentable.md
  - 12 Errors_As_Values.md
  - 13 Pattern_Matching.md
  - 14 Advanced_Typing_Concepts.md
  - 15 Async.md
  - 16 Interoperability_And_Typing_Stubs.md
  - 17 Best_Practices.md
  - A1 Quick_Reference.md
  - A2 Glossary.md
  - A3 Type_Checkers.md
  - A4 Class_Attributes.md
