site_name: Thinking in Types
docs_dir: Chapters
site_url: https://ThinkingInTypes.github.io
repo_url: https://github.com/ThinkingInTypes/ThinkingInTypes.github.io

theme:
  name: material
  favicon: img/favicon.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes  # Ensures only one entry in TOC
    # - toc.integrate  # Makes TOC part of the left-hand navigation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"


nav:
  - 01 Preface.md
  - 02 Introduction.md
  - 03 Basic_Annotations.md
  - 04 Collections.md
  - 05 Generics.md
  - 06 Dataclasses.md
  - 07 Specialized_Type_Tools.md
  - 08 Callable_Types.md
  - 09 Structural_Typing.md
  - 10 Make_Illegal_Types_Unrepresentable.md
  - 11 Errors_As_Values.md
  - 12 Advanced_Typing_Concepts.md
  - 13 Pattern_Matching_And_Typing.md
  - 14 Async.md
  - 15 Interoperability_And_Typing_Stubs.md
  - 16 Best_Practices.md
  - A1 Quick_Reference.md
  - A2 Glossary.md
  - A3 Type_Checkers.md
