site_name: Thinking in Types
docs_dir: Chapters
site_url: https://ThinkingInTypes.github.io
repo_url: https://github.com/ThinkingInTypes/ThinkingInTypes_Book

theme:
  name: material
  favicon: img/favicon.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes  # Ensures only one entry in TOC
    # - toc.integrate  # Makes TOC part of the left-hand navigation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"


nav:
  - 01 Preface.md
  - 02 Introduction.md
  - 03 Basic Annotations.md
  - 04 Collections.md
  - 05 Generics.md
  - 06 Dataclasses.md
  - 07 Specialized Type Tools.md
  - 08 Callable Types.md
  - 09 Tools And Techniques.md
  - 10 Structural Typing.md
  - 11 Make Illegal Types Unrepresentable.md
  - 12 Errors As Values.md
  - 13 Advanced Typing Concepts.md
  - 14 Pattern Matching And Typing.md
  - 15 Typing And Async Programming.md
  - 16 Interoperability And Typing Stubs.md
  - 17 Best Practices Patterns And AntiPatterns.md
  - Appendices.md
